// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uxfwurwidepfgocrjble.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV4Znd1cndpZGVwZmdvY3JqYmxlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA4MTY2MTksImV4cCI6MjA4NjM5MjYxOX0.aEt1LSTGxswrhJ464OzhnXWB73vHYtBmn8ZzMFsmmec";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});